config/routes.rb
UmPorCento::Application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/quem-somos', to: 'pages#about', as: :quem_somos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_filter :load_resources

  def home
    @slides = [
      {url: "slides/slide-3.jpg", caption_1: "Que você andou", caption_2: "de bicicleta?", title: "Pessoal"},
      {url: "slides/slide-2.jpg", caption_1: "Que você abraçou", caption_2: "alguém de verdade?", title: "Interpessoal"},
      {url: "slides/slide-4.jpg", caption_1: "Que você brincou", caption_2: "com seus filhos?", title: "Familiar"},
      {url: "slides/slide-1.jpg", caption_1: "Que você se dedicou", caption_2: "a uma causa nobre?", title: "Social"}
    ]
    @comumCircle = [
      {title: "Somos um/uma", words: %w(marca símbolo movimento comunidade bandeira insígnia grupo nome ideia rede)},
      {title: "100%", words: %w(compartilhada open\ source autônoma gratuita livre aberta coletiva distribuída colaborativa auto-gestionada)},
      {title: "Que faz", words: %w(arte ações projetos negócios tecnologia comunicação encontros produtos serviços coisas)}
    ]
  end

  def about
    @team = [
      {picture: "people/ale.png", role: "Pássaro", name: "Ale", surname: "Moesh"},
      {picture: "people/anderson.png", role: "Pássaro", name: "Anderson", surname: "Mirapalheta"},
      {picture: "people/angel.png", role: "Fundador", name: "Angel", surname: "Mirapalheta"},
      {picture: "people/carmem.png", role: "Pássaro", name: "Carmem", surname: "Barbosa"},
      {picture: "people/dario.png", role: "Pássaro", name: "Dário", surname: "Rushel"},
      {picture: "people/diego.png", role: "Pássaro", name: "Diego", surname: "Marchi"},
      {picture: "people/emilia.png", role: "Pássaro", name: "Emília", surname: "Adachi"},
      {picture: "people/lu.png", role: "Pássaro", name: "Lu", surname: "Xerxenevsky"},
      {picture: "people/luiza.png", role: "Pássaro", name: "Luiza", surname: "Prigol"},
      {picture: "people/mari.png", role: "Pássaro", name: "Mari", surname: "Fraga"},
      {picture: "people/matthias.png", role: "Pássaro", name: "Matthias", surname: "Schneider"},
      {picture: "people/vanessa.png", role: "Pássaro", name: "Vanessa", surname: "Kukul"}
    ]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html.no-js lang="en" 
  head
    meta charset="utf-8" /
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" /
    meta http-equiv="X-UA-Compatible" content="IE=edge" /
    title= content_for?(:title) ? yield(:title) : "Um Por Cento"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "vendor/modernizr"
    link rel="shortcut icon" type="image/x-icon" href="favicon.ico"
    link rel="apple-touch-icon" href="webclip.png"
    = csrf_meta_tags
  body
    = initjs_tag "UmPorCento"
    = link_to "Ir ao conteúdo principal", "#content", class: "sr-only sr-only-focusable"
    = render partial: 'shared/menu'
    .main-content#main-content
      = yield
    = render partial: 'shared/footer'
    = javascript_include_tag "application"

app/views/pages/_slider.html.slim
.home-slider.cycle-slideshow data-cycle-fx="fadeout" data-cycle-timeout="6000" data-cycle-slides=".slide" data-cycle-speed="800" data-cycle-pager-template="<li class=slider-pager-item><a href=#>{{cycleTitle}}</a></li>" data-cycle-log="false"
  .slide-cover
  .slide data-cycle-title="Intro"
    .slider-image-intro
  - @slides.each do |slide|
    .slide data-cycle-title="#{slide[:title]}"
      h4.slider-caption.caption-1= slide[:caption_1]
      h4.slider-caption.caption-2== slide[:caption_2]
      .slider-bg-img style="background-image: url(#{image_path(slide[:url])});"
  ul.cycle-pager.hidden-xs

app/views/pages/about.html.slim
.about-page
  article.text-content.content-section
    .container
      .row
        .col-md-10.col-md-offset-1
          h1.page-title quem somos?
          p Somos uma ideia. Somos uma semente a ser plantada, a ser semeada com muito amor, com muita perseverança, audácia e coragem. Somos você, pai, que dá a devida atenção a um filho, a uma família. Somos você, que se preocupa com o mundo ao seu redor. Somos você que doa roupas, que doa comida, que doa o seu tempo a quem necessita. Somos você governante que age com honestidade, onde o bem comum está acima dos interesses pessoais. 
          p Somos muitos espalhados pelo globo, embora, muitas vezes nem saibamos que todo esse "Povo das Estrelas" seja tão grande assim. Mas lá dentro, no âmago de nossa alma, sabemos que somos muitos. Os bons são maioria. O bem, a verdade e a luz sempre sairão vitoriosos.
          p Pra que você nos identifique com mais exatidão, pra você saciar a sua curiosidade e saber quem realmente somos, iremos deixar claro alguns códigos de nossa tribo, do nosso mundo.
          p Nos reencontramos e nos reconhecemos através do olhar sincero, do abraço amigo. Nos reconectamos na música e na cumplicidade. No riso e na dança. Na arte e na atitude. Na sinceridade e na certeza de estarmos juntos pelo mesmo norte, pelo mesmo propósito. Viemos virar a página da nossa história. Viemos fazer história.<br/> Viemos fazer o bem.
          p Então, afinal, quem somos?
          p 
            | Somos a <strong>UM POR CENTO</strong>.
            br/
            | Somos um pequeno gesto que veio fazer grande diferença nesse mundo.

  section.content-section.dark-bg.dotted-bg
    .container#the-team.the-team
      .row
        .col-md-8.col-md-offset-2
          p "O que há em uma estrela? Nós mesmos! Todos os elementos do nosso corpo e do planeta,      estiveram nas entranhas de uma estrela. Entāo, afinal, quem somos? Somos o povo das            estrelas..." Ernesto Cardenal
      .row
        .col-md-12.team-profiles
          - @team.shuffle.each do |person|
            - if [*1..100].sample < 15
              .teammate.blank-teammate
            .teammate
              = image_tag person[:picture]
              .teammate-info
                .role= person[:role]
                p.fullname
                  strong.name= person[:name].upcase
                  strong.surname= person[:surname].upcase

app/views/pages/home.html.slim
.home-page
  = render partial: 'slider'
  section.content-section.section-comum
    .container
      .row
        - @comumCircle.each_with_index do |circle,index|
          .col-sm-4.column
            .animated-section data-offset="0"
              h4.comum-title.move-up.fade-in= circle[:title]
            .animated-section data-offset="350" data-offset-mobile="0"
              - classes = %w(fly-from-right \  fly-from-left)
              ul.comum-list.list-unstyled class="#{classes[index]}"
                - circle[:words].each do |word|
                  li.list-item= word
      .row
        = link_to "Comum.cc", "http://comum.cc/", class: "comum-link", target: :blank


  section.content-section.dark-bg.dotted-bg
    .container.container-14-minutes
      .row.animated-section data-offset="250"
        h2.heading-14-minutes.fly-from-left.fade-in 14 minutos
        .image-14-minutes
          = image_tag "clock.png", class: "img-responsive rotate-ccw fade-in"
        h2.heading-14-minutes.left.fly-from-right.fade-in.slow-transition 24 segundos
      .animated-section data-offset="150"
        .row.fade-in.move-up.slow-transition
          h3 Este é o tempo exato de apenas 1% do seu dia.
          h3.highlight Dedique ao próximo, a você mesmo!
        .row.fade-in.move-up.delayed-transition.slowest-transition
          p.paragraph-14-minutes
            | Medite. Relaxe. Respire profundamente.
            br/
            | Deixe o turbilhão do mundo passar. Deixe a brisa leve dos ventos te inspirar.

app/views/shared/_footer.html.slim
footer.dark-bg#footer
  .container
    .row
      .col-md-3.contact-mail
        = mail_to "contato@umporcento.org"
      .col-md-9.copyright
        small
          | Designed by 
          = link_to "Diego Polly", "http://www.bohlam.com.br/", target: :blank
          |  and Built by 
          = link_to "Gustavo Guichard", "http://gustavoguichard.com", target: :blank
          |  · 
          = link_to "Open Source", "https://github.com/gustavoguichard/umporcento", target: :blank

app/views/shared/_menu.html.slim
#construction-alert.alert.alert-warning role="alert"
  strong Página em construção. 
  | Pedimos desculpas pelo inconveniente, mas estamos trabalhando nisso ;)

#main-menu
  aside#floating-menu
    a.menu-toggl href="#main-menu"
      span.menu-hamburguer
    = link_to "/", class: "logo" do
      = image_tag "logo.png"
  
  nav.main-menu-content
    = image_tag "passaro.png", class: "bird-image"
    ul.menu.call-to-actions
      li.menu-item= link_to "Quem Somos", quem_somos_path
      li.menu-item= link_to "O que fazemos", "#", data: {construction: true}
      li.menu-item= link_to "Como Ajudar", "#", data: {construction: true}
    ul.menu.secondary-menu
      li.menu-item= link_to "Inspirações", "#", data: {construction: true}
      li.menu-item= link_to "Parceiros", "#", data: {construction: true}
      li.menu-item= link_to "Notícias", "#", data: {construction: true}
      li.menu-item= link_to "Loja", "#", data: {construction: true}
      li.menu-item= link_to "Contato", "#", data: {construction: true}
    footer.menu-bottom
      ul.menu.language-menu.list-inline
        li.menu-item.active= link_to "Por", "#"
        li.menu-item= link_to "Esp", "#", data: {construction: true}
        li.menu-item= link_to "Eng", "#", data: {construction: true}
      ul.menu.social-menu.list-inline
        li.menu-item= link_to "Facebook", "https://www.facebook.com/umporcento.org", class: "social-menu-item facebook", target: :blank
        li.menu-item= link_to "Instagram", "http://instagram.com/UmPorCentoOrg", class: "social-menu-item instagram", target: :blank
        li.menu-item= link_to "Blog", "https://medium.com/@umporcento", target: :blank
        li.menu-item= link_to "YouTube", "https://www.youtube.com/user/UmPorCentoORG", class: "social-menu-item youtube", target: :blank
        li.menu-item= link_to "Vimeo", "https://vimeo.com/umporcentoorg", class: "social-menu-item vimeo", target: :blank